#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git config --get alias.internal-check > /dev/null 2>&1; then
    git internal-check

    if [ $? -ne 0 ]; then
        echo "Internal check failed"
        exit 1
    fi
fi

npx lint-staged
